specfile_path: python-rpm-head-signing.spec

files_to_sync:
    - python-rpm-head-signing.spec
    - .packit.yaml
create_pr: false
sync_changelog: true

upstream_package_name: rpm-head-signing
upstream_project_url: https://github.com/fedora-iot/rpm-head-signing
downstream_package_name: python-rpm-head-signing

actions:
    get-current-version: 'python3 setup.py --version'

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
      - fedora-all
      - epel-8-x86_64
- job: propose_downstream
  trigger: release

