on:
- push
- pull_request

name: Continuous integration

jobs:
  tests_fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          dnf install -y python3-six python3-koji python3-pyxattr python3-rpm make gcc rpm-sign cpio python3-setuptools rpm-devel python3-devel python3-cryptography valgrind

      - name: Build insertlib
        run: |
          python3 setup.py build_ext -i

      - name: Run tests
        run: PRINT_VALGRIND_LOG=1 python3 test.py

  tests_centos_8:
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
          dnf install -y python3-six python3-koji python3-rpm make gcc rpm-sign cpio python3-setuptools rpm-devel python3-devel python3-cryptography valgrind
          pip3 install pyxattr

      - name: Build insertlib
        run: |
          python3 setup.py build_ext -i

      - name: Run tests
        run: PRINT_VALGRIND_LOG=1 python3 test.py

  tests_centos_7:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          yum install -y python2-six python2-koji make gcc rpm-sign cpio python2-setuptools rpm-devel python2-devel python2-pip ima-evm-utils zstd python2-cryptography valgrind
          pip install pyxattr

      - name: Build insertlib
        run: |
          python setup.py build_ext -i

      - name: Run tests
        run: |
          ONLY_ALTERNATIVE_EVMCTL_CHECK=true PRINT_VALGRIND_LOG=1 python test.py
