on:
- push
- pull_request

name: Continuous integration

jobs:
  tests_fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          dnf install -y python3-six python3-koji python3-pyxattr python3-rpm make gcc rpm-sign cpio python3-setuptools rpm-devel python3-devel

      - name: Build insertlib
        run: |
          python3 setup.py build_ext -i

      - name: Run tests
        run: python3 test.py
